### ISSUE TITLE
Error during pmis installation

### ISSUE THREAD

**Issue by rjay1018** [projectexpert/pmis#11]
Got this Error during Project PMIS Installation
![pmis](https://cloud.githubusercontent.com/assets/5526244/19796497/6e863548-9d17-11e6-8f35-d6b7378885df.png)

**Comment by sysadminmatmoz** [comment]
Was that a fresh installation or an update? If it was an update, you'll probably need an update=all

**Comment by hassoon3** [comment]
Same here, but with fresh installation. The id "timebox_daily" is defined in project_gtd module. The full id "project_gtd.timebox_daily" must be used instead.

**Comment by sysadminmatmoz** [comment]
The problem was related to the demo data. Solved now.
