### ISSUE TITLE
Error: null value in column "name" violates not-null constraint when installing project_wbs_gtd v8.0

### ISSUE THREAD

**Issue by hassoon3** [projectexpert/pmis#13]
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (48, AA047, 2016-11-14 15:55:51.000969, null, 1, 1, null, 1, 1, 2016-11-14, null, 1, 1, open, null, contract, null, 2016-11-14 15:55:51.000969, null, null, null, t, t, f, f, null, null, 1, null, null, null, f, null, 2016-11-14, f, f, f, 1, monthly, null, null, null, null, null, null, null, 3).
" while parsing /usr/lib/python2.7/dist-packages/openerp_custom/addons/pmis/project_wbs_gtd/project_gtd_demo.xml:14, near
<record id="project.wbselement_10" model="project.project">
        <field name="timebox_id" ref="project_gtd.timebox_daily"/>
        <field name="context_id" ref="project_gtd.context_office"/>
    </record>

![capture](https://cloud.githubusercontent.com/assets/3623938/20271542/2538b072-aa9c-11e6-8a12-6c66ce2ac707.PNG)

**Comment by hassoon3** [comment]
While installing fresh project_wbs_gtd

**Comment by sysadminmatmoz** [comment]
Yes. Sorry. I didn't do any necessary changes on the demo data to follow the changes on the actual code. It should be solved now (since I don't use the demo at all).
