### ISSUE TITLE
There is no "planned hours" field when opening or editing a task

### ISSUE THREAD

**Issue by leosantiago123** [projectexpert/pmis#14]
In the basic project management app of Odoo is possible to insert the estimated / planned hours for each task you create. The PMIS module I've installed don't have this field, but yet show some fields for calculating the remaining hours for each task. Is that something I'm missing? Or PMIS project module doesn't come with this basic feature?

**Comment by sysadminmatmoz** [comment]
You can find it in the task form, note tab Extra Info:
![screenshot_2017-01-04_17-00-46](https://cloud.githubusercontent.com/assets/6734798/21648858/cf9dc3ec-d29f-11e6-86aa-208ff91f42ed.png)
