### ISSUE TITLE
Gantt view

### ISSUE THREAD

**Issue by beatrizlana-br** [projectexpert/pmis#15]
Hi, I got some issues with the Gantt View for Project > Tasks. I'm not sure if I'm doing something wrong, but could ye help me figuring it out?
When I clicked Project > Portfolio > Work Packages I got it right:
http://imgur.com/a/cAIsf

But when I click Project > Tasks  the start and end dates don't show up, like this:
http://imgur.com/a/a7JRq
And getting P0.D1 as an example, I have a deadline for that:
http://imgur.com/a/kXhji

So what I am missing? Or am I doing something wrong?

Thanks in advance.

**Comment by sysadminmatmoz** [comment]
From what I can see in the screenshots, you didn't set the task duration, which is the base for the end date. The task deadline (in the task form) is not considered as the task end date, it's just a reminder for the last accepted date by the customer, the actual end date is calculated through the calculation network considering the limitations and duration set in the Extra Info tab (task form):
![screenshot_2017-03-08_05-54-41](https://cloud.githubusercontent.com/assets/6734798/23690676/e1291e18-03c3-11e7-97a9-dd8294bf1eef.png)
In the example above, the earliest possible start date is set, the duration is set, the rest is calculated by calculate network.

**Comment by beatrizlana-br** [comment]
Thanks a million @sysadminmatmoz
