### ISSUE TITLE
how to install pmis

### ISSUE THREAD

**Issue by jeffery9** [projectexpert/pmis#2]
i try to install pims, but there have too many dependency need to install. what is the road map to install those addons, can you give out the list of the repo. eg:  git@github.com:sysadminmatmoz/knowledge.git

many thanks for this great project. thanks again.

**Comment by sysadminmatmoz** [comment]
Hi. With the last commit you shouldn't have any more problems; all other dependencies are relative to the OCA repositories (https://github.com/OCA), like for example https://github.com/OCA/web. The Gantt diagram is from https://github.com/stephane-/gantt_improvement.
