### ISSUE TITLE
project_wbs is not migrated to 10.0

### ISSUE THREAD

**Issue by ovnicraft** [projectexpert/pmis#25]
**Describe the bug**

Try to install `project_wbs_task`, system raise error `project_wbs` does not exist
`project_wbs` is not present in 10.0 repository

**To Reproduce**
1. Go to applications and try to install `project_web_task`

**Expected behavior**
Clean installation of module

**Comment by sysadminmatmoz** [comment]
project_wbs is present in the OCA project repository. Closing.
