### ISSUE TITLE
Confirmation of analytic resource plan - version to be used

### ISSUE THREAD

**Issue by JordiBForgeFlow** [projectexpert/pmis#4]
Hi,

When the Analytic Resource Plan line is confirmed it will create analytic plan lines in the active planning version defined in the analytic account.

This can be a problem for companies that do not really take into account the planned costs resulting from the resource plan, and want to use as active version one that has planned costs and revenues entered manually (for example, a version 'Approved Budget').

I propose that we introduce a new field in the planning version that defines what version is the default to be used by the resource plan. As a consequence, the Resource Plan will only use that version when creating the Planned Costs and Revenues.

The active planning version defined in the analytic account will be used only to decide which planned costs and revenues will be listed in the analytic account list view.

**Comment by sysadminmatmoz** [comment]
I agree. The analytic account defined planning version will be for information purposes (example WIP statement) and the default planning version will be the one used for the actual moves. Seems a reasonable approach.
